import assert from "node:assert/strict";
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";

import { installQoder, looksLikeEphemeralNpxCache, qoderMcpConfig, QODER_SERVER_NAME } from "../../src/qoder.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");

async function temporaryDirectory() {
  return fs.mkdtemp(path.join(os.tmpdir(), "chilon-qoder-"));
}

test("renders a stdio server entry Qoder can load", () => {
  const config = qoderMcpConfig({ node: "node", root: "/opt/chilon-recall" });
  const server = config.mcpServers[QODER_SERVER_NAME];

  assert.equal(server.command, "node");
  assert.deepEqual(server.args, [path.join("/opt/chilon-recall", "scripts", "cli.mjs"), "mcp"]);
  assert.match(server.env.RAG_MANAGER_CONFIG, /^<absolute path/);
  assert.equal(Object.keys(server.env).length, 1);
});

test("installs skills and rules without writing credentials", async () => {
  const directory = await temporaryDirectory();
  try {
    const result = await installQoder(directory, { node: "node" });
    const bundled = (await fs.readdir(path.join(root, "skills"), { withFileTypes: true }))
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name)
      .sort();
    const installed = (await fs.readdir(path.join(directory, ".qoder", "skills"))).sort();

    assert.deepEqual(installed, bundled);
    for (const name of bundled) {
      const source = await fs.readFile(path.join(root, "skills", name, "SKILL.md"), "utf8");
      const copied = await fs.readFile(path.join(directory, ".qoder", "skills", name, "SKILL.md"), "utf8");
      assert.equal(copied, source);
    }

    const rule = await fs.readFile(path.join(directory, ".qoder", "rules", "chilon-recall.md"), "utf8");
    assert.match(rule, /rag_status/);

    for (const file of result.written) {
      const content = await fs.readFile(file, "utf8");
      assert.doesNotMatch(content, /\b(?:sk|sf)-[A-Za-z0-9_-]{20,}\b/);
    }
    assert.ok(result.written.length >= bundled.length + 2);
  } finally {
    await fs.rm(directory, { recursive: true, force: true });
  }
});

test("detects an npx temporary cache root by its `_npx` cache segment", () => {
  assert.equal(
    looksLikeEphemeralNpxCache(
      path.join("C:", "Users", "ROG", "AppData", "Local", "npm-cache", "_npx", "96c86a08a0f332a4", "node_modules", "chilon-recall")
    ),
    true
  );
  assert.equal(looksLikeEphemeralNpxCache(path.join(os.tmpdir(), "_npx", "abc123", "node_modules", "chilon-recall")), true);
  assert.equal(looksLikeEphemeralNpxCache("/opt/chilon-recall"), false);
  assert.equal(looksLikeEphemeralNpxCache(root), false);
});

async function copyDirectory(source, destination) {
  await fs.mkdir(destination, { recursive: true });
  for (const entry of await fs.readdir(source, { withFileTypes: true })) {
    const from = path.join(source, entry.name);
    const to = path.join(destination, entry.name);
    if (entry.isDirectory()) await copyDirectory(from, to);
    else await fs.copyFile(from, to);
  }
}

test("warns in `next` when qoder is generated from an npx cache root, and stays silent otherwise", async () => {
  const cacheDirectory = await temporaryDirectory();
  const npxRoot = path.join(cacheDirectory, "npm-cache", "_npx", "abc123def456", "node_modules", "chilon-recall");
  await copyDirectory(path.join(root, "skills"), path.join(npxRoot, "skills"));

  const npxProjectDirectory = await temporaryDirectory();
  const stableProjectDirectory = await temporaryDirectory();
  try {
    const npxResult = await installQoder(npxProjectDirectory, { node: "node", root: npxRoot });
    assert.equal(npxResult.ephemeral_npx_cache, true);
    assert.ok(npxResult.next.some((line) => line.includes("Warning: this was generated by npx")));
    assert.ok(npxResult.next.some((line) => line.includes(npxRoot)));

    const stableResult = await installQoder(stableProjectDirectory, { node: "node", root });
    assert.equal(stableResult.ephemeral_npx_cache, false);
    assert.ok(!stableResult.next.some((line) => line.includes("Warning: this was generated by npx")));
  } finally {
    await fs.rm(cacheDirectory, { recursive: true, force: true });
    await fs.rm(npxProjectDirectory, { recursive: true, force: true });
    await fs.rm(stableProjectDirectory, { recursive: true, force: true });
  }
});

test("refuses to overwrite generated files without --force", async () => {
  const directory = await temporaryDirectory();
  try {
    await installQoder(directory, { node: "node" });
    await assert.rejects(() => installQoder(directory, { node: "node" }), /already exists/);
    await installQoder(directory, { node: "node", force: true });
  } finally {
    await fs.rm(directory, { recursive: true, force: true });
  }
});
